## conda config: environment.yml
# Create a conda environment using this file with:
# run conda env create (automatically finds environment.yml)
# or conda env create -f environment.yml
# Use this to set up a consistent environment for development and testing
# use poetry to activate each project's environment and manage dependencies
name: exp_poetry
channels:
  - conda-forge
  - nodefaults # Disable default channels to avoid conflicts
dependencies:
  - tree # For visualizing directory structures
  - python>= 3.12 # Specify Python version
  - pip # Use pip for package management within the conda environment
  - poetry # For managing dependencies
  - poetry-plugin-export # To export lock files if needed