[project]
name = "query-refinement-module"
version = "0.1.0"
description = "An AI-powered, domain-agnostic query refinement system for scientific literature search."
authors = [
    {name = "Jesus Dominguez",email = "jesus.dominguez@kcl.ac.uk"}
]
keywords = [
    "query refinement",
    "information retrieval",
    "conversational AI",
    "scientific search",
    "literature search",
    "domain-agnostic",
    "LLM",
    "chatbot"
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyyaml (>=6.0.3,<7.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=8.4.2,<9.0.0)"
]
