"""add_refinement_step_metadata_table

Revision ID: 12b1487a2bbe
Revises: 2638f74414d0
Create Date: 2025-12-16 10:51:39.527418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12b1487a2bbe'
down_revision: Union[str, Sequence[str], None] = '2638f74414d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Upgrade schema to add refinement_step_metadata table.
    
    This table stores comprehensive metadata about each refinement step including:
    - Analysis content and follow-up questions
    - LLM provider and model information
    - Token usage and cost estimates
    - Timing metrics for performance monitoring
    - Status tracking and error handling
    - Flexible JSON field for additional metadata
    """
    # ### commands auto generated by Alembic - please adjust! ###
    # Create refinement_step_metadata table with one-to-one relationship to refinement_steps
    op.create_table('refinement_step_metadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('refinement_step_id', sa.Integer(), nullable=False),
    sa.Column('analysis_result', sa.Text(), nullable=True),
    sa.Column('followup_question', sa.Text(), nullable=True),
    sa.Column('llm_provider', sa.Text(), nullable=True),
    sa.Column('llm_model', sa.Text(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('llm_duration_seconds', sa.Float(), nullable=True),
    sa.Column('processing_duration_seconds', sa.Float(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('additional_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['refinement_step_id'], ['refinement_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refinement_step_metadata_refinement_step_id'), 'refinement_step_metadata', ['refinement_step_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema - remove refinement_step_metadata table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refinement_step_metadata_refinement_step_id'), table_name='refinement_step_metadata')
    op.drop_table('refinement_step_metadata')
    # ### end Alembic commands ###
