"""
RefinementStepMetadata model for tracking detailed pipeline metrics and LLM interactions.

This model captures comprehensive metadata about each refinement step, including:
- Analysis results and content
- LLM provider metadata (tokens, model, duration, cost estimates)
- Status flags and error information
- Timing information for performance monitoring
"""
from sqlalchemy import Column, Integer, Text, DateTime, ForeignKey, Float, JSON
from sqlalchemy.orm import relationship
from datetime import datetime, timezone
from .user import Base


def _utcnow():
    """Return current UTC time (timezone-aware)."""
    return datetime.now(timezone.utc)


class RefinementStepMetadata(Base):
    """
    Extended metadata for refinement steps to track pipeline metrics and LLM usage.
    
    This table stores detailed information about each refinement step execution,
    enabling comprehensive monitoring, cost tracking, and performance analysis
    for the query refinement pipeline.
    
    Attributes:
        id: Primary key
        refinement_step_id: Foreign key to refinement_steps table
        
        # Analysis content
        analysis_result: The actual analysis text generated by the LLM
        followup_question: The follow-up question generated for user interaction
        
        # LLM metadata
        llm_provider: Provider used (e.g., 'openai', 'anthropic')
        llm_model: Model identifier (e.g., 'gpt-4', 'claude-3-opus')
        prompt_tokens: Number of tokens in the prompt
        completion_tokens: Number of tokens in the completion
        total_tokens: Total tokens used (prompt + completion)
        estimated_cost_usd: Estimated cost in USD based on provider pricing
        
        # Timing information
        llm_duration_seconds: Time taken for LLM API call
        processing_duration_seconds: Total processing time including pre/post-processing
        
        # Status and error tracking
        status: Status of the step (e.g., 'completed', 'failed', 'skipped')
        error_message: Error details if the step failed
        retry_count: Number of retries attempted
        
        # Additional metadata (stored as JSON for flexibility)
        additional_metadata: Flexible JSON field for provider-specific or custom data
        
        # Timestamps
        created_at: When this metadata record was created
        updated_at: When this record was last updated
    """
    __tablename__ = "refinement_step_metadata"

    # Primary key and foreign key
    id = Column(Integer, primary_key=True, autoincrement=True)
    refinement_step_id = Column(
        Integer, 
        ForeignKey("refinement_steps.id", ondelete="CASCADE"), 
        nullable=False,
        unique=True,  # One-to-one relationship with RefinementStep
        index=True  # Index for faster lookups
    )

    # Analysis content
    analysis_result = Column(Text, nullable=True)  # The actual analysis content
    followup_question = Column(Text, nullable=True)  # Generated follow-up question

    # LLM metadata - track which model/provider was used
    llm_provider = Column(Text, nullable=True)  # e.g., 'openai', 'anthropic', 'azure'
    llm_model = Column(Text, nullable=True)  # e.g., 'gpt-4-turbo', 'claude-3-opus'
    
    # Token usage - critical for cost tracking
    prompt_tokens = Column(Integer, nullable=True)  # Tokens sent to LLM
    completion_tokens = Column(Integer, nullable=True)  # Tokens received from LLM
    total_tokens = Column(Integer, nullable=True)  # Sum of prompt + completion
    estimated_cost_usd = Column(Float, nullable=True)  # Estimated cost based on usage
    
    # Timing metrics - for performance monitoring
    llm_duration_seconds = Column(Float, nullable=True)  # Time for LLM API call
    processing_duration_seconds = Column(Float, nullable=True)  # Total processing time
    
    # Status tracking
    status = Column(Text, nullable=True, default='pending')  # pending, completed, failed, skipped
    error_message = Column(Text, nullable=True)  # Error details if failed
    retry_count = Column(Integer, nullable=False, default=0)  # Number of retry attempts
    
    # Additional flexible metadata (JSON for extensibility)
    # Can store provider-specific data, custom metrics, etc.
    additional_metadata = Column(JSON, nullable=True)
    
    # Timestamps
    created_at = Column(DateTime, nullable=False, default=_utcnow)
    updated_at = Column(
        DateTime, 
        nullable=False, 
        default=_utcnow,
        onupdate=_utcnow  # Auto-update on modification
    )

    # Relationship to RefinementStep
    refinement_step = relationship(
        "RefinementStep", 
        backref="metadata",  # RefinementStep.metadata will give the metadata object
        uselist=False  # One-to-one relationship
    )

    def __repr__(self):
        """String representation for debugging."""
        return (
            f"<RefinementStepMetadata("
            f"id={self.id}, "
            f"step_id={self.refinement_step_id}, "
            f"status='{self.status}', "
            f"provider='{self.llm_provider}', "
            f"model='{self.llm_model}', "
            f"tokens={self.total_tokens}, "
            f"cost=${self.estimated_cost_usd or 0:.4f}"
            f")>"
        )
    
    def to_dict(self):
        """
        Convert metadata to dictionary for JSON serialization.
        
        Returns:
            Dictionary containing all metadata fields
        """
        return {
            'id': self.id,
            'refinement_step_id': self.refinement_step_id,
            'analysis_result': self.analysis_result,
            'followup_question': self.followup_question,
            'llm_provider': self.llm_provider,
            'llm_model': self.llm_model,
            'prompt_tokens': self.prompt_tokens,
            'completion_tokens': self.completion_tokens,
            'total_tokens': self.total_tokens,
            'estimated_cost_usd': self.estimated_cost_usd,
            'llm_duration_seconds': self.llm_duration_seconds,
            'processing_duration_seconds': self.processing_duration_seconds,
            'status': self.status,
            'error_message': self.error_message,
            'retry_count': self.retry_count,
            'additional_metadata': self.additional_metadata,
            'created_at': self.created_at.isoformat() if self.created_at else None,
            'updated_at': self.updated_at.isoformat() if self.updated_at else None,
        }
