"""
Tests for generated_question and generated_examples persistence features.

Covers:
- update_refinement_step_generated_question() CRUD function
- update_refinement_step_generated_examples() CRUD function
- _persist_generated_question() route helper (persists both question and examples)
- Round-trip: persist via CRUD, read back from DB

These tests verify that question/examples generated by the LLM are saved to the DB
so they survive server restarts and session-TTL expiry, allowing read-only
commands (/steps, /status, /help) to return the current question with clickable
options without triggering a new LLM call.
"""
from types import SimpleNamespace
from unittest.mock import MagicMock, patch, call

import pytest

from query_refinement_module.db.crud import (
    create_query,
    create_query_session,
    create_refinement_step,
    create_user,
    get_refinement_step,
    update_refinement_step_generated_question,
    update_refinement_step_generated_examples,
)
from query_refinement_module.api.routes.refinement import _persist_generated_question


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _make_user_and_step(db):
    """Create the minimum DB hierarchy: user → session → query → step."""
    user = create_user(
        db,
        username="test_gq_user",
        email="test_gq@example.com",
        password="ValidPass123!",
        name="GQ Test User",
    )
    qs = create_query_session(db, user_id=user.id)
    query = create_query(db, session_id=qs.id, original_query="test query")
    step = create_refinement_step(db, query_id=query.id, aspect_name="Population", aspect_id="population")
    return step


# ---------------------------------------------------------------------------
# CRUD: update_refinement_step_generated_question
# ---------------------------------------------------------------------------

def test_update_refinement_step_generated_question_persists_value(test_db_session):
    """Saving a question to a step can be read back from the DB."""
    step = _make_user_and_step(test_db_session)
    assert step.generated_question is None

    question = "What is the target population for your query?"
    updated = update_refinement_step_generated_question(
        test_db_session, step.id, question
    )

    assert updated is not None
    assert updated.generated_question == question

    # Verify by re-fetching from DB (not just in-memory object)
    refreshed = get_refinement_step(test_db_session, step.id)
    assert refreshed.generated_question == question


def test_update_refinement_step_generated_question_can_overwrite(test_db_session):
    """A subsequent save replaces the previous question."""
    step = _make_user_and_step(test_db_session)

    update_refinement_step_generated_question(test_db_session, step.id, "First question?")
    update_refinement_step_generated_question(test_db_session, step.id, "Updated question?")

    refreshed = get_refinement_step(test_db_session, step.id)
    assert refreshed.generated_question == "Updated question?"


def test_update_refinement_step_generated_question_returns_none_for_missing_step(test_db_session):
    """Returns None gracefully when the step ID does not exist."""
    result = update_refinement_step_generated_question(test_db_session, step_id=99999, question="x")
    assert result is None


# ---------------------------------------------------------------------------
# Route helper: _persist_generated_question
# ---------------------------------------------------------------------------

def test_persist_generated_question_noop_when_next_prompt_is_none():
    """`next_prompt=None` returns immediately without touching the DB."""
    db_mock = MagicMock()
    _persist_generated_question(db_mock, db_steps=[], next_prompt=None)
    db_mock.assert_not_called()


def test_persist_generated_question_noop_when_db_is_none():
    """`db=None` returns immediately (guard against un-injected sessions)."""
    _persist_generated_question(
        db=None,
        db_steps=[SimpleNamespace(aspect_id="population", aspect_name="Population", id=1)],
        next_prompt={"aspect_id": "population", "name": "Population", "question": "What population?"},
    )
    # No exception raised is the assertion; nothing to assert on a None db.


def test_persist_generated_question_noop_when_aspect_not_in_steps():
    """When no db_step matches the aspect_name, the CRUD function is not called."""
    db_mock = MagicMock()
    db_steps = [SimpleNamespace(aspect_id="intervention", aspect_name="Intervention", id=2)]

    with patch(
        "query_refinement_module.api.routes.refinement.update_refinement_step_generated_question"
    ) as mock_crud:
        _persist_generated_question(
            db_mock,
            db_steps=db_steps,
            next_prompt={"aspect_id": "population", "name": "Population", "question": "What population?"},
        )
        mock_crud.assert_not_called()


def test_persist_generated_question_calls_crud_when_aspect_matches():
    """When a step with the matching aspect_name exists, the CRUD function is called."""
    db_mock = MagicMock()
    db_steps = [
        SimpleNamespace(aspect_id="intervention", aspect_name="Intervention", id=10),
        SimpleNamespace(aspect_id="population", aspect_name="Population", id=7),
    ]

    with patch(
        "query_refinement_module.api.routes.refinement.update_refinement_step_generated_question"
    ) as mock_crud:
        _persist_generated_question(
            db_mock,
            db_steps=db_steps,
            next_prompt={"aspect_id": "population", "name": "Population", "question": "Who are the patients?"},
        )
        mock_crud.assert_called_once_with(db_mock, 7, "Who are the patients?")


def test_persist_generated_question_noop_when_prompt_missing_question_key():
    """A next_prompt dict with no 'question' key is a noop."""
    db_mock = MagicMock()
    db_steps = [SimpleNamespace(aspect_id="population", aspect_name="Population", id=1)]

    with patch(
        "query_refinement_module.api.routes.refinement.update_refinement_step_generated_question"
    ) as mock_crud:
        _persist_generated_question(
            db_mock,
            db_steps=db_steps,
            next_prompt={"aspect_id": "population", "name": "Population"},  # missing 'question'
        )
        mock_crud.assert_not_called()


def test_persist_generated_question_works_when_prompt_has_only_aspect_id():
    """A stable aspect_id is sufficient to persist the generated question."""
    db_mock = MagicMock()
    db_steps = [SimpleNamespace(aspect_id="population", aspect_name="Population", id=1)]

    with patch(
        "query_refinement_module.api.routes.refinement.update_refinement_step_generated_question"
    ) as mock_crud:
        _persist_generated_question(
            db_mock,
            db_steps=db_steps,
            next_prompt={"aspect_id": "population", "question": "Who are the patients?"},
        )
        mock_crud.assert_called_once_with(db_mock, 1, "Who are the patients?")


def test_persist_generated_question_swallows_crud_exception():
    """Exceptions from the CRUD call are caught and logged, never re-raised."""
    db_mock = MagicMock()
    db_steps = [SimpleNamespace(aspect_id="population", aspect_name="Population", id=1)]

    with patch(
        "query_refinement_module.api.routes.refinement.update_refinement_step_generated_question",
        side_effect=RuntimeError("DB exploded"),
    ):
        # Should not raise
        _persist_generated_question(
            db_mock,
            db_steps=db_steps,
            next_prompt={"aspect_id": "population", "name": "Population", "question": "Who?"},
        )


def test_persist_generated_question_falls_back_to_legacy_aspect_name():
    """Legacy rows without aspect_id still match by aspect_name."""
    db_mock = MagicMock()
    db_steps = [SimpleNamespace(aspect_id=None, aspect_name="Population", id=11)]

    with patch(
        "query_refinement_module.api.routes.refinement.update_refinement_step_generated_question"
    ) as mock_crud:
        _persist_generated_question(
            db_mock,
            db_steps=db_steps,
            next_prompt={"aspect_id": "population", "name": "Population", "question": "Who?"},
        )
        mock_crud.assert_called_once_with(db_mock, 11, "Who?")


# ---------------------------------------------------------------------------
# CRUD: update_refinement_step_generated_examples
# ---------------------------------------------------------------------------

def test_update_refinement_step_generated_examples_persists_list(test_db_session):
    """Saving quick-reply examples to a step can be read back from the DB."""
    step = _make_user_and_step(test_db_session)
    assert step.generated_examples is None

    examples = ["elderly patients (65+)", "working-age adults (18-64)", "children under 12"]
    updated = update_refinement_step_generated_examples(test_db_session, step.id, examples)

    assert updated is not None
    assert updated.generated_examples == examples

    refreshed = get_refinement_step(test_db_session, step.id)
    assert refreshed.generated_examples == examples


def test_update_refinement_step_generated_examples_can_overwrite(test_db_session):
    """A subsequent save replaces previous examples."""
    step = _make_user_and_step(test_db_session)

    update_refinement_step_generated_examples(test_db_session, step.id, ["option A", "option B"])
    update_refinement_step_generated_examples(test_db_session, step.id, ["new option X", "new option Y"])

    refreshed = get_refinement_step(test_db_session, step.id)
    assert refreshed.generated_examples == ["new option X", "new option Y"]


def test_update_refinement_step_generated_examples_empty_list(test_db_session):
    """An empty list is a valid value and overwrites previous non-empty data."""
    step = _make_user_and_step(test_db_session)
    update_refinement_step_generated_examples(test_db_session, step.id, ["a", "b"])
    update_refinement_step_generated_examples(test_db_session, step.id, [])

    refreshed = get_refinement_step(test_db_session, step.id)
    assert refreshed.generated_examples == []


def test_update_refinement_step_generated_examples_returns_none_for_missing_step(test_db_session):
    """Returns None gracefully when the step ID does not exist."""
    result = update_refinement_step_generated_examples(test_db_session, step_id=99999, examples=["x"])
    assert result is None


# ---------------------------------------------------------------------------
# Route helper: _persist_generated_question — examples branch
# ---------------------------------------------------------------------------

def test_persist_generated_question_also_persists_examples():
    """When next_prompt includes examples, the examples CRUD is called too."""
    db_mock = MagicMock()
    db_steps = [SimpleNamespace(aspect_id="population", aspect_name="Population", id=7)]

    with patch(
        "query_refinement_module.api.routes.refinement.update_refinement_step_generated_question"
    ), patch(
        "query_refinement_module.api.routes.refinement.update_refinement_step_generated_examples"
    ) as mock_examples_crud:
        _persist_generated_question(
            db_mock,
            db_steps=db_steps,
            next_prompt={
                "aspect_id": "population",
                "name": "Population",
                "question": "Who are the patients?",
                "examples": ["elderly patients", "working-age adults", "children"],
            },
        )
        mock_examples_crud.assert_called_once_with(
            db_mock, 7, ["elderly patients", "working-age adults", "children"]
        )


def test_persist_generated_question_skips_examples_when_empty():
    """When examples list is empty, the examples CRUD is not called."""
    db_mock = MagicMock()
    db_steps = [SimpleNamespace(aspect_id="population", aspect_name="Population", id=7)]

    with patch(
        "query_refinement_module.api.routes.refinement.update_refinement_step_generated_question"
    ), patch(
        "query_refinement_module.api.routes.refinement.update_refinement_step_generated_examples"
    ) as mock_examples_crud:
        _persist_generated_question(
            db_mock,
            db_steps=db_steps,
            next_prompt={
                "aspect_id": "population",
                "name": "Population",
                "question": "Who are the patients?",
                "examples": [],
            },
        )
        mock_examples_crud.assert_not_called()


def test_persist_generated_question_swallows_examples_crud_exception():
    """Exceptions from the examples CRUD are caught and logged, never re-raised."""
    db_mock = MagicMock()
    db_steps = [SimpleNamespace(aspect_id="population", aspect_name="Population", id=7)]

    with patch(
        "query_refinement_module.api.routes.refinement.update_refinement_step_generated_question"
    ), patch(
        "query_refinement_module.api.routes.refinement.update_refinement_step_generated_examples",
        side_effect=RuntimeError("DB exploded"),
    ):
        # Should not raise
        _persist_generated_question(
            db_mock,
            db_steps=db_steps,
            next_prompt={
                "aspect_id": "population",
                "name": "Population",
                "question": "Who?",
                "examples": ["option A"],
            },
        )
