"""
Tests for the generated_question persistence feature.

Covers:
- update_refinement_step_generated_question() CRUD function
- _persist_generated_question() route helper
- Round-trip: persist via CRUD, read back from DB

These tests verify that a question generated by the LLM is saved to the DB
so that it survives server restarts and session-TTL expiry, allowing read-only
commands (/steps, /status, /help) to return the question without a new LLM call.
"""
from types import SimpleNamespace
from unittest.mock import MagicMock, patch, call

import pytest

from query_refinement_module.db.crud import (
    create_query,
    create_query_session,
    create_refinement_step,
    create_user,
    get_refinement_step,
    update_refinement_step_generated_question,
)
from query_refinement_module.api.routes.refinement import _persist_generated_question


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _make_user_and_step(db):
    """Create the minimum DB hierarchy: user → session → query → step."""
    user = create_user(
        db,
        username="test_gq_user",
        email="test_gq@example.com",
        password="ValidPass123!",
        name="GQ Test User",
    )
    qs = create_query_session(db, user_id=user.id)
    query = create_query(db, session_id=qs.id, original_query="test query")
    step = create_refinement_step(db, query_id=query.id, aspect_name="Population")
    return step


# ---------------------------------------------------------------------------
# CRUD: update_refinement_step_generated_question
# ---------------------------------------------------------------------------

def test_update_refinement_step_generated_question_persists_value(test_db_session):
    """Saving a question to a step can be read back from the DB."""
    step = _make_user_and_step(test_db_session)
    assert step.generated_question is None

    question = "What is the target population for your query?"
    updated = update_refinement_step_generated_question(
        test_db_session, step.id, question
    )

    assert updated is not None
    assert updated.generated_question == question

    # Verify by re-fetching from DB (not just in-memory object)
    refreshed = get_refinement_step(test_db_session, step.id)
    assert refreshed.generated_question == question


def test_update_refinement_step_generated_question_can_overwrite(test_db_session):
    """A subsequent save replaces the previous question."""
    step = _make_user_and_step(test_db_session)

    update_refinement_step_generated_question(test_db_session, step.id, "First question?")
    update_refinement_step_generated_question(test_db_session, step.id, "Updated question?")

    refreshed = get_refinement_step(test_db_session, step.id)
    assert refreshed.generated_question == "Updated question?"


def test_update_refinement_step_generated_question_returns_none_for_missing_step(test_db_session):
    """Returns None gracefully when the step ID does not exist."""
    result = update_refinement_step_generated_question(test_db_session, step_id=99999, question="x")
    assert result is None


# ---------------------------------------------------------------------------
# Route helper: _persist_generated_question
# ---------------------------------------------------------------------------

def test_persist_generated_question_noop_when_next_prompt_is_none():
    """`next_prompt=None` returns immediately without touching the DB."""
    db_mock = MagicMock()
    _persist_generated_question(db_mock, db_steps=[], next_prompt=None)
    db_mock.assert_not_called()


def test_persist_generated_question_noop_when_db_is_none():
    """`db=None` returns immediately (guard against un-injected sessions)."""
    _persist_generated_question(
        db=None,
        db_steps=[SimpleNamespace(aspect_name="Population", id=1)],
        next_prompt={"name": "Population", "question": "What population?"},
    )
    # No exception raised is the assertion; nothing to assert on a None db.


def test_persist_generated_question_noop_when_aspect_not_in_steps():
    """When no db_step matches the aspect_name, the CRUD function is not called."""
    db_mock = MagicMock()
    db_steps = [SimpleNamespace(aspect_name="Intervention", id=2)]

    with patch(
        "query_refinement_module.api.routes.refinement.update_refinement_step_generated_question"
    ) as mock_crud:
        _persist_generated_question(
            db_mock,
            db_steps=db_steps,
            next_prompt={"name": "Population", "question": "What population?"},
        )
        mock_crud.assert_not_called()


def test_persist_generated_question_calls_crud_when_aspect_matches():
    """When a step with the matching aspect_name exists, the CRUD function is called."""
    db_mock = MagicMock()
    db_steps = [
        SimpleNamespace(aspect_name="Intervention", id=10),
        SimpleNamespace(aspect_name="Population", id=7),
    ]

    with patch(
        "query_refinement_module.api.routes.refinement.update_refinement_step_generated_question"
    ) as mock_crud:
        _persist_generated_question(
            db_mock,
            db_steps=db_steps,
            next_prompt={"name": "Population", "question": "Who are the patients?"},
        )
        mock_crud.assert_called_once_with(db_mock, 7, "Who are the patients?")


def test_persist_generated_question_noop_when_prompt_missing_question_key():
    """A next_prompt dict with no 'question' key is a noop."""
    db_mock = MagicMock()
    db_steps = [SimpleNamespace(aspect_name="Population", id=1)]

    with patch(
        "query_refinement_module.api.routes.refinement.update_refinement_step_generated_question"
    ) as mock_crud:
        _persist_generated_question(
            db_mock,
            db_steps=db_steps,
            next_prompt={"name": "Population"},  # missing 'question'
        )
        mock_crud.assert_not_called()


def test_persist_generated_question_noop_when_prompt_missing_name_key():
    """A next_prompt dict with no 'name' key is a noop."""
    db_mock = MagicMock()
    db_steps = [SimpleNamespace(aspect_name="Population", id=1)]

    with patch(
        "query_refinement_module.api.routes.refinement.update_refinement_step_generated_question"
    ) as mock_crud:
        _persist_generated_question(
            db_mock,
            db_steps=db_steps,
            next_prompt={"question": "Who are the patients?"},  # missing 'name'
        )
        mock_crud.assert_not_called()


def test_persist_generated_question_swallows_crud_exception():
    """Exceptions from the CRUD call are caught and logged, never re-raised."""
    db_mock = MagicMock()
    db_steps = [SimpleNamespace(aspect_name="Population", id=1)]

    with patch(
        "query_refinement_module.api.routes.refinement.update_refinement_step_generated_question",
        side_effect=RuntimeError("DB exploded"),
    ):
        # Should not raise
        _persist_generated_question(
            db_mock,
            db_steps=db_steps,
            next_prompt={"name": "Population", "question": "Who?"},
        )
